import { jsPDF } from 'jspdf';
import dincharyaData from '../data/dincharya.json';
import dietData from '../data/diet_recommendations.json';
import exerciseData from '../data/exercise_recommendations.json';
import ritucharyaData from '../data/ritucharya.json';

const DOSHA_LABELS = { vata: 'Vata', pitta: 'Pitta', kapha: 'Kapha' };
const COLORS = { vata: [124, 158, 178], pitta: [192, 112, 74], kapha: [107, 143, 113] };
const EARTH = [44, 36, 24];
const MUTED = [92, 77, 51];
const LIGHT = [156, 134, 96];

function hex(r, g, b) { return [r, g, b]; }

export function generateLifestyleGuidePDF(dominant, dual, type, percentages) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = 210;
  const margin = 18;
  const contentW = W - margin * 2;
  let y = 0;

  const color = COLORS[dominant];

  function setFont(style = 'normal', size = 10) {
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
  }

  function setColor(rgb) { doc.setTextColor(...rgb); }
  function setDrawColor(rgb) { doc.setDrawColor(...rgb); }
  function setFillColor(rgb) { doc.setFillColor(...rgb); }

  function checkPage(needed = 20) {
    if (y + needed > 275) {
      doc.addPage();
      y = 18;
    }
  }

  function sectionTitle(text) {
    checkPage(18);
    y += 6;
    setFillColor(color);
    doc.rect(margin, y, 3, 5, 'F');
    setFont('bold', 13);
    setColor(EARTH);
    doc.text(text, margin + 6, y + 4);
    y += 12;
    setDrawColor([232, 220, 200]);
    doc.line(margin, y, W - margin, y);
    y += 5;
  }

  function subHeading(text) {
    checkPage(10);
    setFont('bold', 9);
    setColor(LIGHT);
    doc.text(text.toUpperCase(), margin, y);
    y += 5;
  }

  function bodyText(text, indent = 0) {
    setFont('normal', 9);
    setColor(MUTED);
    const lines = doc.splitTextToSize(text, contentW - indent);
    lines.forEach((line) => {
      checkPage(5);
      doc.text(line, margin + indent, y);
      y += 4.5;
    });
  }

  function bullet(text, indent = 4, checkmark = false) {
    checkPage(5);
    setFont('normal', 9);
    setColor(MUTED);
    const marker = checkmark ? '✓' : '·';
    const lines = doc.splitTextToSize(text, contentW - indent - 5);
    doc.text(marker, margin + indent, y);
    lines.forEach((line, i) => {
      if (i > 0) checkPage(5);
      doc.text(line, margin + indent + 5, y);
      y += 4.5;
    });
  }

  // ── COVER PAGE ────────────────────────────────────────────────────────────
  // Top colour band
  setFillColor(color);
  doc.rect(0, 0, W, 55, 'F');

  setFont('bold', 28);
  doc.setTextColor(255, 255, 255);
  doc.text('Ayurveda', margin, 24);
  setFont('normal', 28);
  doc.text('Lifestyle Guide', margin, 36);

  setFont('normal', 11);
  doc.setTextColor(255, 255, 255, 0.8);
  doc.text('Personalised for your Prakriti', margin, 47);

  y = 68;

  // Prakriti label
  const prakritiLabel =
    type === 'tridoshic'
      ? 'Tridoshic (Sama Prakriti)'
      : type === 'dual'
      ? `${DOSHA_LABELS[dominant]}–${DOSHA_LABELS[dual]}`
      : `${DOSHA_LABELS[dominant]} Prakriti`;

  setFont('bold', 20);
  setColor(EARTH);
  doc.text(prakritiLabel, margin, y);
  y += 8;

  // Dosha percentages
  setFont('normal', 10);
  setColor(LIGHT);
  const pctLine = Object.entries(percentages)
    .sort((a, b) => b[1] - a[1])
    .map(([d, v]) => `${DOSHA_LABELS[d]} ${v}%`)
    .join('   ·   ');
  doc.text(pctLine, margin, y);
  y += 12;

  setDrawColor([232, 220, 200]);
  doc.line(margin, y, W - margin, y);
  y += 8;

  // Disclaimer box
  setFillColor([253, 246, 242]);
  setDrawColor([232, 180, 154]);
  doc.roundedRect(margin, y, contentW, 28, 3, 3, 'FD');
  setFont('bold', 8);
  setColor([122, 58, 30]);
  doc.text('⚠  Important Notice', margin + 4, y + 6);
  setFont('normal', 8);
  setColor(MUTED);
  const disclaimer =
    'This guide is for educational purposes only and does not constitute medical advice. Consult a qualified Ayurvedic practitioner before starting any herbal protocol. The key principles are moderation and body awareness — observe how your body responds.';
  const dlines = doc.splitTextToSize(disclaimer, contentW - 8);
  dlines.forEach((l, i) => { doc.text(l, margin + 4, y + 12 + i * 4.5); });
  y += 36;

  // Contents list
  setFont('bold', 10);
  setColor(EARTH);
  doc.text('Contents', margin, y);
  y += 6;
  ['1.  Dincharya — Daily Routine', '2.  Ritucharya — Seasonal Guide', '3.  Ahara — Diet Recommendations', '4.  Vyayama — Exercise Guide'].forEach((item) => {
    bullet(item, 0);
  });

  // Footer
  setFont('normal', 8);
  setColor(LIGHT);
  doc.text('Generated by Ayurveda Prakriti · rehanas.github.io/ayurveda-prakriti', margin, 287);

  // ── PAGE 2: DINCHARYA ─────────────────────────────────────────────────────
  doc.addPage();
  y = 18;
  sectionTitle('Dincharya — Daily Routine');

  const dinData = dincharyaData.dincharya[dominant];
  if (dinData) {
    subHeading(`Theme: ${dinData.theme}`);
    y += 2;
    dinData.routine.forEach((item) => {
      checkPage(14);
      setFont('bold', 9);
      setColor(color);
      doc.text(`${item.time}  `, margin, y);
      setFont('bold', 9);
      setColor(EARTH);
      doc.text(item.activity, margin + 22, y);
      if (item.duration) {
        setFont('normal', 8);
        setColor(LIGHT);
        doc.text(`[${item.duration}]`, margin + 22 + doc.getTextWidth(item.activity) + 2, y);
      }
      y += 5;
      bodyText(item.details, 22);
      y += 2;
    });
  }

  // ── RITUCHARYA ────────────────────────────────────────────────────────────
  doc.addPage();
  y = 18;
  sectionTitle('Ritucharya — Seasonal Guide');

  ritucharyaData.ritucharya.seasons.forEach((season) => {
    checkPage(40);
    const rec = season.recommendations[dominant];
    if (!rec) return;

    setFont('bold', 10);
    setColor(EARTH);
    doc.text(season.name, margin, y);
    setFont('normal', 8);
    setColor(LIGHT);
    doc.text(`${season.months}  ·  ${season.climate}`, margin, y + 5);
    y += 10;

    [['Diet', rec.diet], ['Lifestyle', rec.lifestyle], ['Exercise', rec.exercise], ['Herbs', rec.herbs]].forEach(([label, text]) => {
      subHeading(label);
      bodyText(text, 4);
      y += 1;
    });
    y += 4;
    setDrawColor([232, 220, 200]);
    doc.line(margin, y, W - margin, y);
    y += 6;
  });

  // ── DIET ──────────────────────────────────────────────────────────────────
  doc.addPage();
  y = 18;
  sectionTitle('Ahara — Diet Recommendations');

  const diet = dietData.dietRecommendations[dominant];
  if (diet) {
    bodyText(diet.generalPrinciples);
    y += 3;

    subHeading('Tastes to Favour');
    diet.tastes.favor.forEach((t) => bullet(t, 4, true));
    y += 2;
    subHeading('Tastes to Reduce');
    diet.tastes.reduce.forEach((t) => bullet(t, 4));
    y += 4;

    subHeading('Meal Guidelines');
    Object.entries(diet.mealGuidelines).forEach(([meal, desc]) => {
      checkPage(12);
      setFont('bold', 9);
      setColor(EARTH);
      const label = meal.charAt(0).toUpperCase() + meal.slice(1);
      doc.text(`${label}:`, margin + 4, y);
      y += 4.5;
      bodyText(desc, 8);
      y += 1;
    });
    y += 3;

    subHeading('Food Categories');
    Object.entries(diet.foodCategories).forEach(([cat, data]) => {
      checkPage(20);
      setFont('bold', 9);
      setColor(EARTH);
      const label = cat.charAt(0).toUpperCase() + cat.slice(1);
      doc.text(label, margin + 4, y);
      y += 5;

      if (data.favor?.length) {
        setFont('bold', 8);
        setColor([107, 143, 113]);
        doc.text('Favour:', margin + 8, y);
        y += 4;
        data.favor.slice(0, 6).forEach((f) => bullet(f, 12, true));
      }
      if (data.avoid?.length) {
        setFont('bold', 8);
        setColor([192, 112, 74]);
        doc.text('Avoid:', margin + 8, y);
        y += 4;
        data.avoid.slice(0, 6).forEach((a) => bullet(a, 12));
      }
      y += 2;
    });
  }

  // ── EXERCISE ──────────────────────────────────────────────────────────────
  doc.addPage();
  y = 18;
  sectionTitle('Vyayama — Exercise Guide');

  const ex = exerciseData.exerciseRecommendations[dominant];
  if (ex) {
    bodyText(ex.principle);
    y += 3;

    // Stats row
    setFillColor([243, 237, 224]);
    doc.roundedRect(margin, y, contentW, 16, 2, 2, 'F');
    setFont('bold', 8); setColor(LIGHT);
    doc.text('INTENSITY', margin + 4, y + 5);
    doc.text('FREQUENCY', margin + 58, y + 5);
    doc.text('BEST TIME', margin + 118, y + 5);
    setFont('normal', 9); setColor(EARTH);
    doc.text(ex.intensity, margin + 4, y + 11);
    doc.text(ex.frequency.split(',')[0], margin + 58, y + 11);
    doc.text(ex.bestTiming.split('.')[0], margin + 118, y + 11);
    y += 22;

    subHeading('Capacity Rule');
    bodyText(ex.capacityRule, 4);
    y += 4;

    subHeading('Recommended Activities');
    ex.recommended.forEach((item) => {
      checkPage(14);
      setFont('bold', 9); setColor(EARTH);
      doc.text(`· ${item.activity}`, margin + 4, y);
      setFont('normal', 8); setColor(LIGHT);
      doc.text(`[${item.frequency}]`, margin + 4 + doc.getTextWidth(`· ${item.activity}`) + 2, y);
      y += 5;
      bodyText(item.details, 8);
      y += 1;
    });
    y += 3;

    subHeading('Avoid');
    ex.avoid.forEach((a) => bullet(a, 4));
    y += 3;

    if (ex.yogaPranayama) {
      subHeading('Recommended Asanas');
      bodyText(ex.yogaPranayama.asanas.join('  ·  '), 4);
      y += 3;
      subHeading('Pranayama');
      bodyText(ex.yogaPranayama.pranayama.join('  ·  '), 4);
    }
  }

  // Page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 2; i <= pageCount; i++) {
    doc.setPage(i);
    setFont('normal', 8);
    setColor(LIGHT);
    doc.text(`${prakritiLabel} Lifestyle Guide`, margin, 287);
    doc.text(`${i} / ${pageCount}`, W - margin, 287, { align: 'right' });
  }

  doc.save(`Ayurveda_Lifestyle_Guide_${DOSHA_LABELS[dominant]}.pdf`);
}
